{application,fink_example,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,compiler,syntax_tools,inets,
                             goldrush]},
              {mod,{fink_example_app,[]}},
              {env,[]},
              {modules,[fink_example_app,fink_example_sup,texample]}]}.
